language: python
python:
  - "2.7"

before_install:
  - apt-get install -y python-eventlet
  - pip install -r requirements.txt
  - pip install pytest pytest-cov pylint
  - pip install coveralls

# command to install dependencies
script:
  - pylint kujira/
  - py.test tests/
after_success:
    - coveralls

branches:
  only:
    - travis_test
